name: compilation

on:
  pull_request:
    branches-ignores:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-CPP-500-NAN-5-1-rtype-alexandre.guillard.git"
  EXECUTABLES: "./r-type_client,./r-type_server"

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          trash=$(find -regextype posix-extended -regex "^(.*(\.[oa]|(so)|(gc((no)|(da)|(ov)))|(~)|(\/tmp\/.+))|(#.+#))$")
          bool=0
          for trash in $trash
          do
              echo "::error file=${trash},title=Unwanted file detected:: ${trash}"
              bool=1
          done
          if [ "$bool" == 1 ]
          then
              exit 1
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_repository_cleanliness
    container:
      image: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: compilation program
      run: |
        cmake -B ./build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && cmake --build build
        OIFS=$IFS
        IFS=','
        sep=$EXECUTABLES
        for sep in $sep
        do
            check=""
            check=$(find -wholename ${sep})
            if [[ ${check} == "" || ! -x "$check" ]]
            then
                exit 1
            fi
        done
    - name: test run
      run: |
        cd build
        ctest --output-on-failure
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
