name: deploy_doc

on:
  push:
    branches:
      - main

jobs:

  deploy_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.DOC_TOKEN_RTYPE }}