name: deploy_doc

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-CPP-500-NAN-5-1-rtype-alexandre.guillard.git"

jobs:

  deploy_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.DOC_TOKEN_RTYPE }}
  push_to_mirror:
    runs-on: ubuntu-latest
    needs: deploy_doc
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
